
import { LandingLayout } from '@/components/layout/LandingLayout';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from '@/components/ui/card';

const faqItems = [
  {
    question: "What is Trendsetter Pro?",
    answer: "Trendsetter Pro is an all-in-one platform that provides a suite of specialized AI agents designed to automate and supercharge your content strategy, SEO, and sales prospecting workflows. It helps you discover trends, analyze competitors, generate high-quality content, and find new leads."
  },
  {
    question: "How do the 'AI Agents' work?",
    answer: "Each 'agent' is a specialized AI model fine-tuned for a specific task (e.g., finding trends, analyzing articles, extracting contact data). Our platform uses an 'agentic' approach, where we can chain these agents together. For example, the Trend Agent can find a topic, which is then passed to the Content Agent to write an article, creating a powerful, automated workflow."
  },
  {
    question: "Is the generated content unique and SEO-friendly?",
    answer: "Yes. The content generated by our AI is unique and created based on your specific inputs. Our prompts are engineered to produce SEO-optimized content, including proper use of HTML tags (headings, lists, etc.) and metadata suggestions for popular SEO plugins like Yoast and AIOSEO."
  },
  {
    question: "Can I use this for sales and lead generation?",
    answer: "Absolutely. The Autonomous Prospecting agent is specifically designed for this. You can provide a URL (like a company's 'About Us' or 'Team' page), and the agent will crawl it to extract company details, key personnel, roles, and publicly available contact information, saving it to your prospects list."
  },
  {
    question: "What is the difference between the Basic and Pro plans?",
    answer: "The Basic plan is great for individuals and small teams, offering a generous amount of credits for each tool. The Pro plan provides unlimited access to most of our agents, a higher limit for article generation, and API access for custom integrations, making it ideal for professionals and businesses."
  },
  {
    question: "Do you use my data to train your AI models?",
    answer: "No. We value your privacy and intellectual property. Your inputs (like topics or competitor URLs) and the content generated for you are not used to train our AI models. Please see our Privacy Policy for more details."
  },
  {
    question: "How do I publish content to my WordPress site?",
    answer: "Our Content Creation hub features a one-click 'Publish' button. When configured, this sends the generated article, its title, metadata, and even the AI-generated featured image directly to your WordPress site as a new post draft via a secure webhook. You need to install our companion plugin on your WordPress site to enable this."
  }
];

export default function FaqPage() {
  return (
    <LandingLayout>
      <section className="container py-12 md:py-20">
        <Card className="max-w-3xl mx-auto shadow-lg">
          <CardHeader className="text-center">
            <CardTitle className="text-3xl font-bold">Frequently Asked Questions</CardTitle>
            <CardDescription>
              Find answers to common questions about Trendsetter Pro.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Accordion type="single" collapsible className="w-full">
              {faqItems.map((item, index) => (
                <AccordionItem key={index} value={`item-${index}`}>
                  <AccordionTrigger className="text-lg text-left">{item.question}</AccordionTrigger>
                  <AccordionContent className="text-base text-muted-foreground">
                    {item.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </CardContent>
        </Card>
      </section>
    </LandingLayout>
  );
}
