import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const faqItems = [
  {
    question: "What is Trendsetter Pro?",
    answer: "Trendsetter Pro is an all-in-one platform that provides a suite of specialized AI agents designed to automate and supercharge your content strategy and SEO workflows. It helps you discover trends, analyze competitors, and generate high-quality content."
  },
  {
    question: "How do the 'AI Agents' work?",
    answer: "Each 'agent' is a specialized AI model fine-tuned for a specific task (e.g., finding trends, analyzing articles). Our platform uses an 'agentic' approach, where we can chain these agents together. For example, the Trend Agent can find a topic, which is then passed to the Content Agent to write an article, creating a powerful, automated workflow."
  },
  {
    question: "Is the generated content unique and SEO-friendly?",
    answer: "Yes. The content generated by our AI is unique and created based on your specific inputs. Our prompts are engineered to produce SEO-optimized content that aligns with Google's E-E-A-T guidelines, including proper use of HTML tags and metadata suggestions for popular SEO plugins like Yoast and AIOSEO."
  },
  {
    question: "How does the Competitor Analyzer work?",
    answer: "You provide the URL of a competitor's article, and our agent crawls the page, analyzes the content, and generates a 'report card.' This report includes key topics, a content grade, a summary of the article's tone, and, most importantly, a list of 'content gaps'—related sub-topics the competitor missed that you can use to create a more comprehensive article."
  },
  {
    question: "What is the difference between the Basic and Pro plans?",
    answer: "The Basic plan is great for individuals and small teams, offering a generous amount of credits for each tool. The Pro plan provides unlimited access to most of our agents, a higher limit for article generation, and API access for custom integrations, making it ideal for professionals and businesses."
  },
  {
    question: "How do I publish content to my WordPress site?",
    answer: "Our Content Creation hub features a one-click 'Publish' button. When configured, this sends the generated article, its title, metadata, and even the AI-generated featured image directly to your WordPress site as a new post draft via a secure webhook. You need to install our companion plugin on your WordPress site to enable this."
  }
];

export function FaqSection() {
    return (
        <section className="bg-muted/50">
            <div className="container py-16 md:py-24">
                <div className="mx-auto flex max-w-3xl flex-col items-center space-y-4 text-center mb-12">
                    <h2 className="font-bold text-3xl leading-[1.1] sm:text-3xl md:text-5xl text-foreground">Frequently Asked Questions</h2>
                </div>
                <div className="max-w-3xl mx-auto">
                    <Accordion type="single" collapsible className="w-full space-y-2">
                    {faqItems.map((item, index) => (
                        <AccordionItem key={index} value={`item-${index}`} className="bg-card border rounded-lg shadow-sm">
                        <AccordionTrigger className="text-lg text-left hover:no-underline px-6">
                            {item.question}
                        </AccordionTrigger>
                        <AccordionContent className="text-base text-muted-foreground px-6 pb-6">
                            {item.answer}
                        </AccordionContent>
                        </AccordionItem>
                    ))}
                    </Accordion>
                </div>
            </div>
        </section>
    );
}
