
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

const faqItems = [
  {
    question: "How does Trendsetter Pro adapt to Google's updates like the 'Muvera' algorithm?",
    answer: "This is at the core of our strategy. Updates like 'Muvera' emphasize rich, multi-modal content. Trendsetter Pro directly addresses this by not only creating E-E-A-T aligned articles but also by enabling you to convert that text into engaging videos with a single click. By helping you build a library of both text and video content, we ensure your strategy is aligned with the future of search."
  },
  {
    question: "What makes Trendsetter Pro different from other AI writers?",
    answer: "Three things: 1) We focus on the entire content lifecycle, from trend discovery to performance analysis. 2) We offer a real-time Content Optimizer with an AI-driven Content Score, giving you instant feedback to improve your on-page SEO. 3) Our core advantage is the 'Performance-Driven Content Loop'—the AI analyzes your content's results and gets smarter, providing recommendations to improve your strategy over time. This creates a competitive moat for your business."
  },
  {
    question: "How does the Content Optimizer and Content Score work?",
    answer: "Our Content Optimizer is like having an SEO expert over your shoulder. As you write, you get real-time metrics on word count and keyword density. When you're ready, the AI performs a deep analysis and gives you a 'Content Score' from 0-100. It also provides actionable recommendations and a list of NLP-friendly keywords to include, helping you create perfectly optimized content."
  },
  {
    question: "Is the generated content unique and SEO-friendly?",
    answer: "Yes. The content generated by our AI is unique and created based on your specific inputs. Our prompts are engineered to produce SEO-optimized content that aligns with Google's E-E-A-T guidelines, including proper use of HTML tags and metadata suggestions for popular SEO plugins like Yoast and AIOSEO."
  },
  {
    question: "How do I publish content to my WordPress site (or other platforms)?",
    answer: "We use a flexible and powerful integration with Zapier. Instead of being locked into just WordPress with a specific plugin, you can connect Trendsetter Pro to thousands of apps. You simply create a 'Zap' that listens for when you publish an article in our app and then tells Zapier to create a new post in WordPress, Ghost, Webflow, Google Docs, or any other platform you use. This gives you complete control over your workflow."
  },
   {
    question: "How does the Competitor Analyzer work?",
    answer: "You provide the URL of a competitor's article, and our agent crawls the page, analyzes the content, and generates a 'report card.' This report includes key topics, a content grade, a summary of the article's tone, and, most importantly, a list of 'content gaps'—related sub-topics the competitor missed that you can use to create a more comprehensive article."
  }
];

export function FaqSection() {
    return (
        <section className="bg-muted/50">
            <div className="container py-16 md:py-24">
                <div className="mx-auto flex max-w-3xl flex-col items-center space-y-4 text-center mb-12">
                    <h2 className="font-bold text-3xl leading-[1.1] sm:text-3xl md:text-5xl text-foreground">Frequently Asked Questions</h2>
                </div>
                <div className="max-w-3xl mx-auto">
                    <Accordion type="single" collapsible className="w-full space-y-2">
                    {faqItems.map((item, index) => (
                        <AccordionItem key={index} value={`item-${index}`} className="bg-card border rounded-lg shadow-sm">
                        <AccordionTrigger className="text-lg text-left hover:no-underline px-6">
                            {item.question}
                        </AccordionTrigger>
                        <AccordionContent className="text-base text-muted-foreground px-6 pb-6">
                            {item.answer}
                        </AccordionContent>
                        </AccordionItem>
                    ))}
                    </Accordion>
                </div>
            </div>
        </section>
    );
}
