
import { LandingLayout } from '@/components/layout/LandingLayout';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';

export default function PrivacyPolicyPage() {
  return (
    <LandingLayout>
      <section className="container py-12 md:py-20">
        <Card className="max-w-3xl mx-auto shadow-lg">
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-center">Privacy Policy</CardTitle>
          </CardHeader>
          <CardContent className="prose dark:prose-invert max-w-none">
            <p className="text-sm text-muted-foreground">Last updated: June 20, 2025</p>
            <p>Your privacy is important to us. This Privacy Policy explains how Trendsetter Pro ("we", "us", or "our") collects, uses, and discloses information about you when you access or use our website and services (collectively, the "Service").</p>

            <h2>1. Information We Collect</h2>
            <p>We collect information you provide directly to us, information we collect automatically, and information from third-party sources.</p>
            <ul>
              <li><strong>Personal Information:</strong> This includes your name, email address, and payment information. Please note that payment information is processed by our third-party payment processors and we do not store it.</li>
              <li><strong>Content:</strong> We collect the text, topics, and files you provide to our AI models ("Inputs") and the content generated by the models in response ("Outputs").</li>
              <li><strong>Usage Information:</strong> We collect information about your use of the Service, such as the features you use, the searches you perform, and the time, frequency, and duration of your activities.</li>
              <li><strong>Log and Device Information:</strong> We log information like your IP address, browser type, operating system, and device information.</li>
            </ul>

            <h2>2. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul>
                <li>Provide, maintain, and improve our Service.</li>
                <li>Process your transactions and manage your subscription.</li>
                <li>Communicate with you about your account and our services.</li>
                <li>Monitor and analyze trends, usage, and activities in connection with our Service.</li>
                <li>Detect, investigate, and prevent fraudulent transactions and other illegal activities and protect the rights and property of Trendsetter Pro and others.</li>
                <li>We do <strong>not</strong> use your Inputs or Outputs to train our AI models.</li>
            </ul>

            <h2>3. Data Sharing and Disclosure</h2>
            <p>We do not share your personal information except in the limited circumstances described below:</p>
            <ul>
              <li><strong>With Service Providers:</strong> We share information with third-party vendors and service providers that perform services for us, such as payment processing (e.g., Stripe) and cloud hosting (e.g., Firebase).</li>
              <li><strong>With AI Sub-processors:</strong> Your Inputs are shared with our AI service providers (e.g., Google's Gemini) to generate the Outputs. Their use of data is governed by their respective privacy policies and terms.</li>
              <li><strong>For Legal Reasons:</strong> We may disclose information if we believe it's required by law, regulation, or legal process.</li>
            </ul>

            <h2>4. Data Retention</h2>
            <p>We store your information for as long as is necessary to provide the Service to you and for our legitimate business purposes. For example, we retain your account information for as long as your account is active and a reasonable period thereafter in case you decide to re-activate the Service.</p>

            <h2>5. Your Data Protection Rights (General)</h2>
            <p>Depending on your location, you may have certain rights regarding your personal information. These may include the right to access, correct, delete, or restrict the processing of your data. To exercise these rights, please contact us.</p>
            
            <h3>For Users in the European Economic Area (EEA) and UK (GDPR)</h3>
            <p>If you are a resident of the EEA or the UK, you have the following data protection rights:</p>
            <ul>
              <li>The right to access, update, or delete the information we have on you.</li>
              <li>The right of rectification.</li>
              <li>The right to object to our processing of your Personal Data.</li>
              <li>The right of restriction.</li>
              <li>The right to data portability.</li>
              <li>The right to withdraw consent at any time.</li>
            </ul>

            <h3>For Users in India (DPDPA)</h3>
            <p>If you are a resident of India, you have rights under the Digital Personal Data Protection Act, 2023, including:</p>
            <ul>
              <li>The right to access a summary of your personal data being processed.</li>
              <li>The right to correct and erase your personal data.</li>
              <li>The right to grievance redressal.</li>
              <li>The right to nominate an individual to exercise your rights in case of your death or incapacity.</li>
            </ul>
            
            <h2>6. Children's Privacy</h2>
            <p>Our Service is not intended for use by children under the age of 16, and we do not knowingly collect personal information from children under 16.</p>

            <h2>7. Changes to This Privacy Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

            <h2>8. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us at: <a href="mailto:privacy@trendsetter.pro">privacy@trendsetter.pro</a> (this is a dummy email).</p>
          </CardContent>
        </Card>
      </section>
    </LandingLayout>
  );
}
